// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy6RkZsPz_9V8EElTt2W9oR_8prcHoPDo',
    appId: '1:515351196586:web:c55076d652630eac35b1d3',
    messagingSenderId: '515351196586',
    projectId: 'healthylife-930bc',
    authDomain: 'healthylife-930bc.firebaseapp.com',
    storageBucket: 'healthylife-930bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDTR5FZTemEMAJt6HJkksL-mM0N_1r94E',
    appId: '1:515351196586:android:b3bd00375fbadf5a35b1d3',
    messagingSenderId: '515351196586',
    projectId: 'healthylife-930bc',
    storageBucket: 'healthylife-930bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAjQrRxFp7ekHCA5mFiNuLz89uMauRXPQ',
    appId: '1:515351196586:ios:22e332503319e5b835b1d3',
    messagingSenderId: '515351196586',
    projectId: 'healthylife-930bc',
    storageBucket: 'healthylife-930bc.firebasestorage.app',
    iosBundleId: 'com.example.lifeSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAjQrRxFp7ekHCA5mFiNuLz89uMauRXPQ',
    appId: '1:515351196586:ios:22e332503319e5b835b1d3',
    messagingSenderId: '515351196586',
    projectId: 'healthylife-930bc',
    storageBucket: 'healthylife-930bc.firebasestorage.app',
    iosBundleId: 'com.example.lifeSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy6RkZsPz_9V8EElTt2W9oR_8prcHoPDo',
    appId: '1:515351196586:web:fa8160c5d00652f635b1d3',
    messagingSenderId: '515351196586',
    projectId: 'healthylife-930bc',
    authDomain: 'healthylife-930bc.firebaseapp.com',
    storageBucket: 'healthylife-930bc.firebasestorage.app',
  );
}
